<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-E7BQ14H" failures="2" tests="4" name="TestNG" time="1.126" errors="0" timestamp="2025-03-07T17:09:03 EET">
  <testcase classname="DemoTestNG.DummyTests" name="test1" time="0.009"/>
  <testcase classname="DemoTestNG.DummyTests" name="test2" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at DemoTestNG.DummyTests.test2(DummyTests.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="DemoTestNG.DummyTests" name="test3" time="1.022">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method DemoTestNG.DummyTests.test3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method DemoTestNG.DummyTests.test3() didn't finish within the time-out 1000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at DemoTestNG.DummyTests.test3(DummyTests.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="DemoTestNG.DummyTests" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
</testsuite> <!-- TestNG -->
